gvisor blog
fission/blog.fission.io pull request #61
Opened 2021-02-10 13:05 UTC by RealHarshThakur

Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>

2021-02-23 09:58 UTC, vishal-biyani requested changes
Good except for one comment on content. 

Also if you can find a good example that demonstrates how gVisor ensures security - even if a pointer to example would be good!

2021-02-23 09:58 UTC, vishal-biyani commented on content/posts/gvisor.md
> +Google Kubernetes Engine provides the option of using gVisor out of the box. You need to have a GKE cluster running, after which you can add a new node pool on which gVisor is enabled. The new node p
Can we at least add pointers to how to run this if not on GKE - as not everyone will have GKE

2021-02-23 10:01 UTC, RealHarshThakur commented on content/posts/gvisor.md
> +Google Kubernetes Engine provides the option of using gVisor out of the box. You need to have a GKE cluster running, after which you can add a new node pool on which gVisor is enabled. The new node p
Sure. I'll add a link to other installations supported by gVisor : https://gvisor.dev/docs/user_guide/quick_start/kubernetes/

2021-02-23 11:11 UTC, sahil-lakhwani commented
@RealHarshThakur The first image doesn't look good, might need resize.

2021-02-25 12:41 UTC, RealHarshThakur commented on content/posts/gvisor.md
> +Google Kubernetes Engine provides the option of using gVisor out of the box. You need to have a GKE cluster running, after which you can add a new node pool on which gVisor is enabled. The new node p
Done,  PTAL

2021-02-25 12:41 UTC, RealHarshThakur commented
@sahil-lakhwani fixed it, thanks for pointing out

2021-04-13 14:12 UTC, merged